version: '3.8'

services:
  mysql:
    image: mysql:5.7.40
    container_name: local_img_bed_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: local_img_bed
      MYSQL_USER: local_img_bed_user
      MYSQL_PASSWORD: your_mysql_password
    ports:
      - "13336:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: local_img_bed_app
    restart: always
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/local_img_bed?useSSL=false&serverTimezone=Asia/Shanghai
      - DB_USERNAME=local_img_bed_user
      - DB_PASSWORD=your_mysql_password
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - IMAGE_STORAGE_ROOT_PATH=/data/images # 新增：告知Spring Boot容器内的图片路径
    volumes:
      - image_data:/data/images # 将图片存储在Docker卷中
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: local_img_bed_frontend
    restart: always

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: local_img_bed_nginx_proxy
    restart: always
    ports:
      - "80:80" # 用户访问的唯一入口
    volumes:
      - image_data:/var/www/images:ro # 以只读方式挂载图片卷，供Nginx读取
    depends_on:
      - app
      - frontend

volumes:
  image_data:
  mysql_data:
