services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: local_img_bed_app
    restart: always
    ports:
      - "8198:8080" # 将主机的 8198 端口映射到容器的 8080 端口
    environment:
      - DB_URL=${DB_URL} # 从 .env 文件读取数据库 jdbc:mysql://127.0.0.1:3306/local_img_bed?useSSL=false&serverTimezone=Asia/Shanghai
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - image_data:/data/images # 将上传的图片存储在名为 image_data 的数据卷中

volumes:
  image_data:
